version: '1.0.0'

services:
  db-psql:
    image: postgres:15-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB_NAME}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
      - POSTGRES_USER=${POSTGRES_DB_USERNAME}
    container_name: crm-postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ./shared-containers:/shared
