name: ci run

on:
  workflow_call:
    inputs:
      codeCoverage:
        required: true
        type: string

jobs: 
  test_and_coverage:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: "checkout code"
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: "test_coverage"
        uses: docker://camistyles/test-node-ci:node-test
        env:
          CI_COVERAGE_MIN: ${{ inputs.codeCoverage }}
        with:
          args: test.sh  
